%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\julia\Documents\Bank_additional.xlsx
%    Worksheet: bank-additional
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/21 13:22:44

%% Import the data
[~, ~, raw] = xlsread('C:\Users\julia\Documents\Bank_additional.xlsx','bank-additional','A2:Y4120');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[2,3,4,5,6,7,8,9,10,15,21]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,11,12,13,14,16,17,18,19,20,22,23,24,25]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
age = data(:,1);
job = categorical(stringVectors(:,1));
marital = categorical(stringVectors(:,2));
education = categorical(stringVectors(:,3));
default = categorical(stringVectors(:,4));
housing = categorical(stringVectors(:,5));
loan = categorical(stringVectors(:,6));
contact = categorical(stringVectors(:,7));
month1 = categorical(stringVectors(:,8));
day_of_week = categorical(stringVectors(:,9));
duration = data(:,2);
campaign = data(:,3);
pdays = data(:,4);
previous = data(:,5);
poutcome = categorical(stringVectors(:,10));
empvarrate = data(:,6);
conspriceidx = data(:,7);
consconfidx = data(:,8);
euribor3m = data(:,9);
nremployed = data(:,10);
y = categorical(stringVectors(:,11));
e = data(:,11);
Defaultbin = data(:,12);
Housingbin = data(:,13);
loanbin = data(:,14);

%% Clear temporary variables
clearvars data raw stringVectors R;